### ISSUE TITLE
Cannot find module 'worker_threads'

### ISSUE THREAD

**Issue by solvek** [SlenkyDev/StopRussia.net.ua#22]
```
$ npm run build

> vite@0.0.0 build xxx/StopRussia.net.ua
> vite build

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (xxx/StopRussia.net.ua/node_modules/vite/dist/node/chunks/dep-36bf480c.js:26:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vite@0.0.0 build: `vite build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vite@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     xxx/.npm/_logs/2022-03-02T16_11_18_569Z-debug.log
```

**Comment by SlenkyDev** [comment]
Probably a problem on your side, works for me and other people working on the project.

**Comment by xHyroM** [comment]
What is your Nodejs version?

**Comment by solvek** [comment]
> What is your Nodejs version?

`
$ nodejs -v
v10.19.0
`

**Comment by solvek** [comment]
> Probably a problem on your side, works for me and other people working on the project.

Yes, you are right....
can anyone help me with problems on my side?

**Comment by xHyroM** [comment]
> > What is your Nodejs version?
> 
> ```
> $ nodejs -v
> v10.19.0
> ```

Update your nodes version to 16.x
